############################
# --- Required options --- #
############################

# Name of website
title: JOONSEOK YANG

# Your name to show in the footer
author: JOONSEOK YANG

###############################################
# --- Navigation Links --- #
###############################################

navbar-links:
  About: "/"
  CV: "cv"
  Research: "research"

################
# --- Logo --- #
################

# Profile image in the navigation bar (optional)
# avatar: "/assets/img/profile-photo.jpg"
round-avatar: true

###########################
# --- General options --- #
###########################

# Remove blog posts and related features
feed_show_excerpt: false
feed_show_tags: false
post_search: false

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude blog posts and related files
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/
