############################
# --- Basic settings --- #
############################
title: "JOONSEOK YANG"
author: JOONSEOK YANG

###############################################
# --- Navigation --- #
###############################################
###############################################
# --- Navigation --- #
###############################################
navbar-links:
  HOME: "/"
  CV: "cv"
  RESEARCH: "research"

# 기존 navbar 색상 설정 제거 또는 수정
navbar-col: ""
navbar-text-col: ""
navbar-border-col: ""

###########################
# --- Layout & Design --- #
###########################
# Colors
navbar-col: "#EAEAEA"  # Light gray for navigation
navbar-text-col: "#404040"  # Dark gray for text
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#666666"

# Layout settings
title-on-all-pages: false
round-avatar: false

###########################
# --- Remove Blog Features --- #
###########################
paginate: 0
post_search: false
feed_show_excerpt: false
feed_show_tags: false

###########################
# --- Exclude Files --- #
###########################
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/
  - docs/

site-css:
  - "/assets/css/custom.css"
  
title-separator: " | "

title: JOONSEOK YANG
description: "Joonseok Yang Associate Professor of Political Science at Sungkyunkwan University"
author: Joonseok Yang
url: "https://joonsyang.github.io"

# SEO 관련 설정
lang: en
locale: en_US
social:
  name: Joonseok Yang
  links:
    - https://github.com/joonsyang

# SEO 태그와 사이트맵 활성화
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# 구글 애널리틱스가 있다면 추가
# google_analytics: UA-XXXXXXXXX-X

  
