# Basic settings
title: "JOONSEOK YANG"
author: JOONSEOK YANG

# Navigation
navbar-links:
  HOME: "/"
  CV: "cv"
  RESEARCH: "research"

# Remove any blog-related settings
paginate: 0
feed_show_excerpt: false
feed_show_tags: false
post_search: false

# Colors
navbar-col: "#8B7765"  # Brown color similar to the example
navbar-text-col: "#FFFFFF"
navbar-border-col: "#8B7765"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#666666"

# Layout
title-on-all-pages: false

# Remove blog-related settings
paginate: 0
feed_show_excerpt: false
feed_show_tags: false
post_search: false

# Exclude blog posts and related files
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/
  - docs/
