############################
# --- Basic settings --- #
############################
title: "JOONSEOK YANG"
author: JOONSEOK YANG

###############################################
# --- Navigation --- #
###############################################
navbar-links:
  About: "/"
  CV: "cv"
  Research: "research"

# Enable variable length for navbar
navbar-var-length: true
navbar-right-padding: 20px   # Add padding to the right of navbar

###########################
# --- Layout & Design --- #
###########################
# Colors
navbar-col: "#EAEAEA"  # Light gray for navigation
navbar-text-col: "#404040"  # Dark gray for text
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#666666"

# Layout settings
title-on-all-pages: false
round-avatar: false

###########################
# --- Remove Blog Features --- #
###########################
paginate: 0
post_search: false
feed_show_excerpt: false
feed_show_tags: false

###########################
# --- Exclude Files --- #
###########################
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/
  - docs/
