############################
# --- Required options --- #
############################

# Name of website
title: Your Name # Replace with your actual name

# Your name to show in the footer
author: Your Name # Replace with your actual name

###############################################
# --- Navigation Links --- #
###############################################

navbar-links:
  About: "/"  # About is now the home page
  CV: "cv"
  Research: "research"

################
# --- Logo --- #
################

# Profile image in the navigation bar (optional)
# avatar: "/assets/img/profile-photo.jpg"  # Uncomment and update path to add your photo
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "your.email@institution.edu"
  github: yourusername
  google-scholar: your-scholar-id
  # orcid: your-orcid-id  # Uncomment if you want to add ORCID
  # twitter: yourusername  # Uncomment if you want to add Twitter

###########################
# --- General options --- #
###########################

# Basic color scheme for an academic website
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#005DAA"  # More professional blue
hover-col: "#004080"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Add a search button to the navbar
post_search: false

# Jekyll configurations
timezone: "America/New_York"  # Adjust to your timezone
markdown: kramdown
permalink: /:title/

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.md"  # This ensures the home page uses the proper layout
    values:
      layout: "home"

# Plugins
plugins:
  - jekyll-sitemap
